name: petitparser_examples
version: 7.0.0

homepage: https://petitparser.github.io
repository: https://github.com/petitparser/dart-petitparser-examples
description: A collection of example parsers, applications, and benchmarks that
  illustrate the PetitParser framework.
topics:
  - grammar
  - parser
  - parser-combinator
  - parsing
  - peg

environment:
  sdk: ^3.8.0
dependencies:
  args: ^2.7.0
  collection: ^1.19.0
  data: ^0.15.0
  http: ^1.4.0
  meta: ^1.16.0
  more: ^4.6.0
  petitparser: ^7.0.0
  web: ^1.1.0
  xml: ^6.6.0
dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.1.0
  lints: ^6.0.0
  test: ^1.26.0
